export interface CatalogService { id:string; displayName:string; domains:string[]; aliases:string[]; category:string; accent:string; secondaryAccent:string; iconStrategy:"neutral-local-mark"; licenseStatus:"no-trademark-asset"; status:"catalog-v1"; }
const groups: Array<[string, string, string[], string[], string]> = [
  ["google","Google",["google.com","gmail.com"],["gmail","google drive","google cloud","gemini"],"identity"],["apple","Apple",["apple.com","icloud.com"],["icloud","apple music"],"identity"],["microsoft","Microsoft",["microsoft.com","outlook.com","live.com","office.com"],["outlook","onedrive","azure","teams"],"identity"],["yahoo","Yahoo",["yahoo.com"],["yahoo mail"],"identity"],["proton","Proton",["proton.me","protonmail.com"],["proton mail"],"identity"],["zoho","Zoho",["zoho.com"],[],"identity"],["fastmail","Fastmail",["fastmail.com"],[],"identity"],
  ["instagram","Instagram",["instagram.com"],[],"social"],["facebook","Facebook",["facebook.com"],[],"social"],["threads","Threads",["threads.net"],[],"social"],["x","X",["x.com","twitter.com"],["twitter"],"social"],["tiktok","TikTok",["tiktok.com"],[],"social"],["snapchat","Snapchat",["snapchat.com"],[],"social"],["linkedin","LinkedIn",["linkedin.com"],[],"social"],["pinterest","Pinterest",["pinterest.com"],[],"social"],["reddit","Reddit",["reddit.com"],[],"social"],["discord","Discord",["discord.com"],[],"social"],["telegram","Telegram",["telegram.org"],[],"social"],["whatsapp","WhatsApp",["whatsapp.com"],[],"social"],
  ["github","GitHub",["github.com"],["gist"],"developer"],["gitlab","GitLab",["gitlab.com"],[],"developer"],["bitbucket","Bitbucket",["bitbucket.org"],[],"developer"],["stackoverflow","Stack Overflow",["stackoverflow.com"],[],"developer"],["docker","Docker",["docker.com","hub.docker.com"],[],"developer"],["npm","npm",["npmjs.com"],[],"developer"],["pypi","PyPI",["pypi.org"],[],"developer"],["vercel","Vercel",["vercel.com"],[],"developer"],["netlify","Netlify",["netlify.com"],[],"developer"],["cloudflare","Cloudflare",["cloudflare.com"],[],"developer"],["supabase","Supabase",["supabase.com"],[],"developer"],["firebase","Firebase",["firebase.google.com"],[],"developer"],["aws","AWS",["aws.amazon.com"],["amazon web services"],"developer"],["digitalocean","DigitalOcean",["digitalocean.com"],[],"developer"],["render","Render",["render.com"],[],"developer"],["railway","Railway",["railway.app"],[],"developer"],
  ["openai","OpenAI",["openai.com","chatgpt.com"],["chatgpt"],"ai"],["anthropic","Anthropic",["anthropic.com","claude.ai"],["claude"],"ai"],["perplexity","Perplexity",["perplexity.ai"],[],"ai"],["huggingface","Hugging Face",["huggingface.co"],[],"ai"],["cursor","Cursor",["cursor.com"],[],"ai"],["replit","Replit",["replit.com"],[],"ai"],["midjourney","Midjourney",["midjourney.com"],[],"ai"],
  ["notion","Notion",["notion.so"],[],"work"],["slack","Slack",["slack.com"],[],"work"],["zoom","Zoom",["zoom.us"],[],"work"],["trello","Trello",["trello.com"],[],"work"],["asana","Asana",["asana.com"],[],"work"],["jira","Jira",["atlassian.net"],[],"work"],["linear","Linear",["linear.app"],[],"work"],["dropbox","Dropbox",["dropbox.com"],[],"work"],["canva","Canva",["canva.com"],[],"work"],["figma","Figma",["figma.com"],[],"work"],["adobe","Adobe",["adobe.com"],[],"work"],
  ["amazon","Amazon",["amazon.com"],[],"shopping"],["ebay","eBay",["ebay.com"],[],"shopping"],["aliexpress","AliExpress",["aliexpress.com"],[],"shopping"],["shopify","Shopify",["shopify.com"],[],"shopping"],["etsy","Etsy",["etsy.com"],[],"shopping"],["daraz","Daraz",["daraz.pk"],[],"shopping"],
  ["paypal","PayPal",["paypal.com"],[],"finance"],["stripe","Stripe",["stripe.com"],[],"finance"],["wise","Wise",["wise.com"],[],"finance"],["payoneer","Payoneer",["payoneer.com"],[],"finance"],["revolut","Revolut",["revolut.com"],[],"finance"],["coinbase","Coinbase",["coinbase.com"],[],"finance"],["jazzcash","JazzCash",["jazzcash.com.pk"],[],"finance"],["easypaisa","Easypaisa",["easypaisa.com.pk"],[],"finance"],["sadapay","SadaPay",["sadapay.pk"],[],"finance"],["nayapay","NayaPay",["nayapay.com"],[],"finance"],["hbl","HBL",["hbl.com"],[],"finance"],["meezan","Meezan Bank",["meezanbank.com"],[],"finance"],["ubl","UBL",["ubl.com.pk"],[],"finance"],["mcb","MCB",["mcb.com.pk"],[],"finance"],["alfalah","Bank Alfalah",["bankalfalah.com"],[],"finance"],
  ["youtube","YouTube",["youtube.com"],[],"streaming"],["netflix","Netflix",["netflix.com"],[],"streaming"],["spotify","Spotify",["spotify.com"],[],"streaming"],["primevideo","Prime Video",["primevideo.com"],[],"streaming"],["disney","Disney+",["disneyplus.com"],[],"streaming"],["twitch","Twitch",["twitch.tv"],[],"streaming"],["steam","Steam",["steampowered.com"],[],"gaming"],["epic","Epic Games",["epicgames.com"],[],"gaming"],["playstation","PlayStation",["playstation.com"],[],"gaming"],["xbox","Xbox",["xbox.com"],[],"gaming"],["nintendo","Nintendo",["nintendo.com"],[],"gaming"],["coursera","Coursera",["coursera.org"],[],"education"],["udemy","Udemy",["udemy.com"],[],"education"],["khan","Khan Academy",["khanacademy.org"],[],"education"],["moodle","Moodle",["moodle.org"],[],"education"],["jazz","Jazz",["jazz.com.pk"],[],"telecom"],["zong","Zong",["zong.com.pk"],[],"telecom"],["ufone","Ufone",["ufone.com"],[],"telecom"],["telenor","Telenor",["telenor.com.pk"],[],"telecom"],["ptcl","PTCL",["ptcl.com.pk"],[],"telecom"]
];
export const serviceCatalog: CatalogService[] = groups.map(([id,displayName,domains,aliases,category],index)=>({id,displayName,domains,aliases,category,accent:["#315a7d","#7b4a69","#465b6f","#5c7050"][index%4],secondaryAccent:"#e7edf2",iconStrategy:"neutral-local-mark",licenseStatus:"no-trademark-asset",status:"catalog-v1"}));
export const genericIdentityCategories=["Email","Social","Bank","Finance","University / Education","Government","Work","Personal","Shopping","Healthcare","Hosting","Developer","AI","Gaming","Streaming","Telecom","Router / Network","Generic Website"] as const;
export function normalizeServiceInput(value:string){return value.trim().toLowerCase().replace(/^https?:\/\//,"").split(/[/?#]/)[0].replace(/^www\./,"");}
export function resolveCatalogService(serviceName:string,domain=""){const input=normalizeServiceInput(domain||serviceName);return serviceCatalog.find(s=>s.domains.some(d=>input===d||input.endsWith(`.${d}`))||s.aliases.some(a=>`${serviceName} ${domain}`.toLowerCase().includes(a))||s.displayName.toLowerCase()===serviceName.trim().toLowerCase());}
